# Generated by Django 5.0.1 on 2024-08-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='samples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_title', models.CharField(max_length=50)),
                ('item_disc', models.CharField(max_length=50)),
            ],
        ),
    ]
