# Generated by Django 5.0.1 on 2024-08-11 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melkamapp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='natural_products',
            fields=[
                ('samples_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='melkamapp.samples')),
            ],
            bases=('melkamapp.samples',),
        ),
    ]
