# Generated by Django 5.0.1 on 2024-08-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melkamapp', '0005_car_spare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samples',
            name='item_img',
            field=models.CharField(max_length=50),
        ),
    ]
