# Generated by Django 5.0.1 on 2024-08-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melkamapp', '0007_alter_samples_item_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('orderd_item', models.CharField(max_length=50)),
                ('amount_item', models.CharField(max_length=50)),
                ('user_number', models.CharField(max_length=50)),
            ],
        ),
    ]
