# Generated by Django 5.0.1 on 2024-08-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melkamapp', '0008_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samples',
            name='item_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
