# Generated by Django 5.0.1 on 2024-08-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melkamapp', '0009_alter_samples_item_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='car_spare_part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_img', models.ImageField(upload_to='')),
                ('item_title', models.CharField(max_length=50)),
                ('item_disc', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='car_spare',
        ),
    ]
